name: Automated tests

on:
  pull_request:
    branches:
      - staging
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/

    - name: Set NPM_TOKEN
      run: echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV

    - name: npm install, test
      run: |
        npm install
        npm test
